from tkinter import *

root = Tk()

#def printName():
#    print("My name is Henry")
#button_1 = Button(root, text="Print my name", command=printName)
#button_1.pack()

title = Label(root, text="Patient Drug Prescription Form")
label_1 = Label(root, text="Full Name")
label_2 = Label(root, text="Email")
label_3 = Label(root, text="Phone Number")
label_4 = Label(root, text="Prescription")
label_5 = Label(root, text="Dosage")
entry_1 = Entry(root)
entry_2 = Entry(root)
entry_3 = Entry(root)
entry_4 = Entry(root)
entry_5 = Entry(root)
title.grid(row=0, columnspan=2)
label_1.grid(row=1, sticky=E)
label_2.grid(row=2, sticky=E)
label_3.grid(row=3, sticky=E)
label_4.grid(row=4, sticky=E)
label_5.grid(row=5, sticky=E)
entry_1.grid(row=1, column=1)
entry_2.grid(row=2, column=1)
entry_3.grid(row=3, column=1)
entry_4.grid(row=4, column=1)
entry_5.grid(row=5, column=1)
submit_button = Button(root, text="Submit", command=print("Submitted"))
submit_button.grid(row=6, columnspan=2)
#c = Checkbutton(root, text="Keep me logged in")
#c.grid(columnspan=2)

#one = Label(root, text="One", bg="red", fg="white")
#one.pack()
#two = Label(root, text="Two", bg="green", fg="black")
#two.pack(fill=X)
#three = Label(root, text="Three", bg="blue", fg="white")
#three.pack(side=LEFT, fill=Y)

#topFrame = Frame(root)
#topFrame.pack()
#bottomFrame = Frame(root)
#bottomFrame.pack(side=BOTTOM)
#button1 = Button(topFrame, text="Button 1", fg="red")
#button2 = Button(topFrame, text="Button 2", fg="blue")
#button3 = Button(topFrame, text="Button 3", fg="green")
#button4 = Button(bottomFrame, text="Button 4", fg="purple")
#button1.pack(side=LEFT)
#button2.pack(side=LEFT)
#button3.pack(side=LEFT)
#button4.pack(side=BOTTOM)

#theLabel = Label(root, text="This is too easy")
#theLabel.pack()

root.mainloop()
